### ISSUE TITLE
Failed to build a docker image

### ISSUE THREAD

**Issue by chirayukong** [czka/archlinux-docker#9]
I got errors like this:

```
usr/share/man/man3/libhavege.3.gz: Failed to set file flags
usr/share/man/man8/haveged.8.gz: Failed to set file flags
bsdtar: Error exit delayed from previous errors.
The command '/bin/sh -c curl -LsS https://www.archlinux.org/packages/extra/${architecture}/haveged/download/ | bsdtar -xf -     && haveged -w 1024     && pacman-key --init     && pacman-key --populate archlinux     && pacman -U --noconfirm --noprogressbar --arch $architecture https://www.archlinux.org/packages/core/${architecture}/sed/download/     && sed -i "s/^Architecture = auto$/Architecture = $architecture/" /etc/pacman.conf     && sed -n 's/^#Server = https/Server = https/p' /etc/pacman.d/mirrorlist > /tmp/mirrorlist     && rankmirrors -n 3 /tmp/mirrorlist | tee /etc/pacman.d/mirrorlist     && rm /tmp/mirrorlist     && pacman -Sy --noconfirm --noprogressbar --quiet --dbonly haveged     && pacman -S --noconfirm --noprogressbar --quiet haveged     && pacman -Su --noconfirm --noprogressbar --quiet gzip awk     && pacman -Rncss --noconfirm --noprogressbar haveged     && rm /.MTREE /.PKGINFO     && paccache -r -k0     && echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen     && locale-gen     && echo 'LANG=en_US.UTF-8' > /etc/locale.conf' returned a non-zero code: 1
```

Any idea what's going on?

I built it on iMac 10.12.4 with python 3.5.3 :: Anaconda 4.4.0 (x86)64).

**Comment by czka** [comment]
"Failed to set file flags" means bsdtar is not able to restore some of the file flags on those 2 files, as they have them in the haveged archive, on your filesystem. This would suggest some sort of incompatibility between the filesystem the archive was created on and the filesystem of yours.

What is the backing filesystem on your Docker storage and your storage driver? See `docker info` output.

Try adding `--no-fflags` to `bsdtar` call in te Dockerfile and let me know if that helps. If it doesn't, please add `-vv` instead, which might reveal some more hints, and paste that verbose bsdtar output in the ticket comment.

**Comment by czka** [comment]
No response from the user. I suppose 5 years should have been enough.
